language: java
jdk:
  - openjdk11

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "spoledge"

git:
  depth: false

branches:
  only:
    - develop
    - /^release\/.*$/

install: true
script: mvn clean verify pmd:pmd spotbugs:spotbugs checkstyle:checkstyle sonar:sonar -Pcoverage
