language: java
jdk:
  - openjdk11

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "spoledge"

install: true
script: mvn clean verify sonar:sonar -Pcoverage
